# -*- coding: utf-8 -*-
"""Video scraping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AheawudOL4GYe2jA9BxefSJ-E8KcuUVk
"""

import subprocess

m3u8_url = "urlhere"
output_file = "video.mp4"

cmd = [
    "ffmpeg",
    "-y",
    "-i", m3u8_url,
    "-c", "copy",
    "-bsf:a", "aac_adtstoasc",
    output_file
]

subprocess.run(cmd, check=True)
print("Download finished")